// Service worker: network first, cache as fallback, so the app works offline.
const CACHE = 'charla-v1';

// PRECACHE:START (generated by scripts/precache.mjs)
const PRECACHE = [
  "./",
  "index.html",
  "manifest.webmanifest",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "icons/icon.svg",
  "src/actions.js",
  "src/app.js",
  "src/core/audio.js",
  "src/core/dates.js",
  "src/core/gemini.js",
  "src/core/prompts.js",
  "src/core/store.js",
  "src/core/themes.js",
  "src/core/transcript.js",
  "src/lib/h.js",
  "src/live/capture-worklet.js",
  "src/live/session.js",
  "src/main.js",
  "src/styles.css",
  "src/views/format.js",
  "src/views/history.js",
  "src/views/keyCard.js",
  "src/views/levelPicker.js",
  "src/views/session.js",
  "src/views/settings.js",
  "src/views/themes.js",
  "src/views/today.js"
];
// PRECACHE:END

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    fetch(req)
      .then((res) => {
        if (res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      })
      .catch(() => caches.match(req, { ignoreSearch: true }).then((hit) => hit ?? caches.match('./'))),
  );
});
